services:
- type: web
  name: rabbitmq
  env: docker
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    sync: false
  - key: RABBITMQ_DEFAULT_USER
    value: rabbitmq
  - key: RABBITMQ_DEFAULT_PASS
    sync: false
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq
    sizeGB: 10
